name = "ParallelTemperingMonteCarlo"
uuid = "3b4a078d-6172-48b3-819b-6f35da58c07f"
authors = ["Elke Pahl <Elke.Pahl@auckland.ac.nz>"]
version = "0.1.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
