name: Run tests

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
    # tags: '*'
  pull_request:
    branches:
      - main
      #- develop
      #- feature/github-actions

jobs:
  testNewVersion:
    runs-on: ${{ matrix.os }}
    # env:
    #   ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      matrix:
        julia-version: [1]
        # julia-arch: [x64, x86]
        julia-arch: [x64]
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
        # 32-bit Julia binaries are not available on macOS
        # exclude:
        #   - os: macOS-latest
        #     julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: "Run tests"
        run: |
          export JULIA_PROJECT=@.
          julia -e "using InteractiveUtils; versioninfo(verbose=true)"
          # Run regular tests
          julia -e "using Pkg; Pkg.test(\"ParallelTemperingMonteCarlo\"; coverage=true);"

      - name: "Process coverage"
        uses: julia-actions/julia-processcoverage@latest
      - name: "Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./lcov.info
        if: ${{ matrix.julia-version == '1' }}
