name: Run tests

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@latest
      - name: Install system libraries
        run: sudo apt-get update && sudo apt-get install -y libblas3 liblapack3 libgfortran5
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@latest
      - name: "Install dependencies"
      - uses: julia-actions/julia-buildpkg@latest
      - name: "Run tests"
      - uses: julia-actions/julia-runtest@latest
      - name: "Process coverage"
        uses: julia-actions/julia-processcoverage@latest
      - name: "Coveralls"
        uses: coverallsapp/github-action@latest
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./lcov.info
        if: ${{ matrix.julia-version == '1' }}
